CREATE TABLE SFHZNUMBERID(
    ID INTEGER,
    TYPE VARCHAR(255),
    NUMBER VARCHAR(255),
    PRIMARY KEY(ID)

);

CREATE TABLE SFHZCUSTOMER (
      ID INTEGER,
      NUMBER_ID INTEGER,
      ADDRESS_ID INTEGER,
      NAME VARCHAR(255),
      SURNAME VARCHAR(255),
      EMAIL VARCHAR(255),
      PHONE_NUMBER VARCHAR(255),
      STATUS VARCHAR(255),
      PRIMARY KEY(ID),
      FOREIGN KEY(NUMBER_ID) REFERENCES SFHZNUMBERID(ID)
  );

CREATE TABLE SFHZADDRESS (
      ID INTEGER,
      COUNTRY VARCHAR(255),
      CITY VARCHAR(255),
      ZIP_CODE VARCHAR(255),
      STREET VARCHAR(255),
      NUMBER INTEGER,
      STATUS VARCHAR(255),
      CUSTOMER_ID INTEGER,
      PRIMARY KEY(ID),
      FOREIGN KEY (CUSTOMER_ID) REFERENCES SFHZCUSTOMER(ID)
  );






