CREATE TABLE SFHZCATEGORY (
      ID INTEGER,
      NAME VARCHAR(255),
      PRIMARY KEY(ID)
  );

  CREATE TABLE SFHZPRODUCT (
      ID INTEGER,
      NAME VARCHAR(255),
      DESCRIPTION VARCHAR(255),
      STOCK DECIMAL,
      PRICE DECIMAL,
      STATUS VARCHAR(255),
      CREATION_DATE DATE,
      CATEGORY_ID INTEGER,
      PRIMARY KEY(ID),
      FOREIGN KEY (CATEGORY_ID) REFERENCES SFHZCATEGORY(ID)
  );

INSERT INTO SFHZCATEGORY (ID, NAME) VALUES (1, 'Smartphones');
INSERT INTO SFHZCATEGORY (ID, NAME) VALUES (2, 'Computers');
INSERT INTO SFHZCATEGORY (ID, NAME) VALUES (3, 'Videoconsoles');

INSERT INTO SFHZPRODUCT(ID, NAME, DESCRIPTION, STOCK, PRICE, STATUS, CREATION_DATE, CATEGORY_ID)
VALUES(1, 'iPhone 13', 'A mobilephone of Apple', 45, 991.99, 'Active', '2022-10-21', 1);

INSERT INTO SFHZPRODUCT(ID, NAME, DESCRIPTION, STOCK, PRICE, STATUS, CREATION_DATE, CATEGORY_ID)
VALUES(2, 'Samsung Galaxy S21 Ultra', 'The best Smartphone!', 22, 965.87, 'Active', '2022-10-21', 1);

INSERT INTO SFHZPRODUCT(ID, NAME, DESCRIPTION, STOCK, PRICE, STATUS, CREATION_DATE, CATEGORY_ID)
VALUES(3, 'Asus ZenBook', 'A computer for programming', 19, 1049.11, 'Out of stock', '2022-10-13', 2);